### PR TITLE
Some Fixes:

### PR DESCRIPTION
**Pull request by maartenheremans**
- Fixed bug in lookahead rule that does not return an error on an invalid token.
- Fixed deprecated warnings

### CODE REVIEW

**Comment by abeschneider** [comment]
Fixes look good, but do you mind undoing some of the indenting changes? I prefer having:

`rule = (group) { action }`

to

`rule = (group){action}`

Thanks!

**Comment by ScottPJones** [comment]
Does it work without the removal of the space between the `)` and the `{`?
There've been some changes in v0.4, at least between `name` `(` and `name` `{` where a space is no longer allowed.

**Comment by abeschneider** [comment]
@ScottPJones That's an excellent question. I haven't had time to test with the previous versions of v0.4, but given that RC1 is out, I will start testing the code with it.

**Comment by maartenheremans** [comment]
The spacing between ) and { gives deprecated warnings in 0.4
So i guess it might start giving issues in next releases.

**Comment by abeschneider** [comment]
Okay, in that case looks good. Thanks for the update.

**Comment by abeschneider** [comment]
I also added the lookahead rule to the README.md.

**Pull request merged**
